spring.application.name=GreenPoint
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/point?currentSchema=app
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
